version: "3"
services:
    # Database
    db:
#        platform: linux/x86_64
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_PASSWORD: root
        networks:
            - mysql-phpmyadmin
    # phpmyadmin
    phpmyadmin:
        depends_on:
            - db
#        platform: linux/x86_64
        image: phpmyadmin
        restart: always
        ports:
            - "8899:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        networks:
            - mysql-phpmyadmin
    # redis
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
    # phpredisadmin
    phpredisadmin:
        depends_on:
            - redis
        image: erikdubbelboer/phpredisadmin:latest
        environment:
            - REDIS_1_HOST=redis #登入位置
            - REDIS_1_PORT=6379
        ports:
            - "8898:80"
networks:
    mysql-phpmyadmin:

volumes:
    db_data:
