<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Support\Facades\Log;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {


        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function report(Throwable $e)
    {
        //透過guard區分log
        if (auth('erp')->check()) {
            Log::channel('erp_exceptions')->error($e->getMessage());
//        } elseif (auth('api')->check()) {
//            Log::channel('api_exceptions')->error($e->getMessage());
        } elseif (auth('operate')->check()) {
            Log::channel('operate_exceptions')->error($e->getMessage());
//        } elseif (auth('front')->check()) {
//            Log::channel('front_exceptions')->error($e->getMessage());
        } else {
            Log::channel('others_exceptions')->error($e->getMessage());
        }

        parent::report($e); // TODO: Change the autogenerated stub
    }

    public function render($request, Throwable $e)
    {
        //APP_DEBUG開啟狀態，直接離開
        if(env("APP_DEBUG")){
            return parent::render($request, $e);
        }
        //透過guard區分log
        if (auth('erp')->check()) {
            return response()->json([
                'code' => 400,
                'message' => $e->getMessage(),
            ], $e->getStatusCode());
//        } elseif (auth('api')->check()) {
//            return response()->json([
//                'code' => 400,
//                'message' => $e->getMessage(),
//            ], 400);
        } elseif (auth('operate')->check()) {
            //使用管理端 /views/operate/errors/404.blade.php
            return view('operate/errors/404');
//        } elseif (auth('front')->check()) {
//            //使用外網統一頁面 /views/errors/404.blade.php
//            return parent::render($request, $e);
        }
        //
        return parent::render($request, $e);
    }
}
