<?php

namespace App\Exceptions;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Database\QueryException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Support\Facades\Log;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {


        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function report(Throwable $e)
    {
        // 第三方造成的錯誤
        // if (auth('erp')->check()) {
        //     Log::channel('erp_log')->info('erp呼叫官網api，造成錯誤，錯誤訊息：' . $e->getMessage());
        // }

//        // 後台登入
//        if (auth('operate')->check()) {
//
//            //資料更新，根據ID去find找不到資料
//            if ($e instanceof ModelNotFoundException) {
//                Log::shareContext([
//                    'shareContext' => "我是API回應的LOG，相信我!",
//                ]);
//                Log::channel('API_LOG')->info('如果是API溝通的LOG，要這樣存入?');
//            }
//        }
//
//        // 前台登入
//        if (auth('web_front')->check()) {
//
//        } else {
//            // 前台未登入
//        }



        return parent::report($e); // TODO: Change the autogenerated stub
    }

    public function render($request, Throwable $e)
    {
        // if (auth('erp')->check()) {
        //     //第三方造成的錯誤
        // }

//        if (auth('operate')->check()) {
//            // 後台登入
//            if ($e instanceof QueryException) {
//                dd("後台報錯： " . $e->getMessage());
//            }
//            //資料更新，根據ID去find找不到資料
//            if ($e instanceof ModelNotFoundException) {
//                dd("後台報錯： " . $e->getMessage());
//                // return view();
//            }
//        }
//
//        if (auth('web_front')->check()) {
//            // 前台登入
//        } else {
//            // 前台未登入
//        }

        return parent::render($request, $e);
    }
}
